### ISSUE TITLE
Missing call! method

### ISSUE THREAD

**Issue by anothermh** [djanowski/redic-pool#6]
I just tried to use redic-pool 1.0.1 with ohm 2.3.0 and was unable to. The console throws a NoMethodError for `call!`. For example:

```
require 'redic/pool'
require 'ohm'
Ohm.redis = Redic::Pool.new('redis://localhost:6379', size: 10)
class Event < Ohm::Model
  attribute :name
  index :name
end
event = Event.create :name => '12345'
```

This returns the following error:

```
NoMethodError: undefined method `call!' for #<Redic::Pool:0x007fa80a4497b0>
    from /ohm-2.3.0/lib/ohm.rb:1356:in `script'
    from /ohm-2.3.0/lib/ohm.rb:1307:in `save'
    from /ohm-2.3.0/lib/ohm.rb:1085:in `create'
    from (irb):8
    from /ruby-2.2.4/bin/irb:11:in `<main>'
```

I added an initializer to my Rails app and patched in a `call!` method:

```
class Redic::Pool
  def call!(*args)
    call(*args)
  end
end
```

And now it works:

```
event = Event.create :name => '12345'
{
    :id => "1"
}
```

This was changed in 
https://github.com/soveran/ohm/commit/03296384adced8926fa39c68a850ba6ca971361f#diff-c5131c4dd0972eeb4457be00b359be14, line 1356, and was documented in https://github.com/soveran/ohm/blob/master/CHANGELOG.md#230.

Will you accept a pull request?

**Comment by scalp42** [comment]
@djanowski any chance you could take a look at this please? Thanks a lot in advance 😃

**Comment by mwpastore** [comment]
Here's a quick fix with some future-proofing. Stick this somewhere in an initializer or your bootup script:

```ruby
class Redic::Pool
  # https://github.com/djanowski/redic-pool/issues/6
  def call!(*args)
    @pool.with do |client|
      client.call!(*args)
    end
  end unless method_defined?(:call!)
end
```
